<a href="https://colab.research.google.com/github/ymk713/Pytorch_study/blob/main/0522)Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 텐서 생성 - from list

In [1]:
import torch
import numpy as np

list_data = [[10,20], [30,40]]

In [2]:
tensor1 = torch.Tensor(list_data)

print(tensor1)
print(f"tensor type: {type(tensor1)}, tensor shape: {tensor1.shape}")
print(f"tensor type: {tensor1.dtype}, tensor device: {tensor1.device}")

tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor type: torch.float32, tensor device: cpu


In [3]:
if torch.cuda.is_available():
    tensor1 = tensor1.to("cuda")

print(f"tensor type: {type(tensor1)}, tensor shape: {tensor1.shape}")
print(f"tensor type: {tensor1.dtype}, tensor device: {tensor1.device}")

tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor type: torch.float32, tensor device: cuda:0


### 텐서 생성 - from numpy

In [5]:
numpy_data = np.array(list_data)
tensor2 = torch.Tensor(numpy_data)

print(tensor2)
print(f'tensor type: {type(tensor2)}, tensor shape: {tensor2.shape}')
print(f'tensor dtype: {tensor2.dtype}, tensor device: {tensor2.device}')

tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cpu


In [8]:
numpy_data = np.array(list_data)
tensor2_1 = torch.from_numpy(numpy_data)

print(tensor2_1)
print(f"tensor type: {type(tensor2_1)}, tensor shape: {tensor2_1.shape}")
print(f"tensor dtype: {tensor2_1.dtype}, tensor device: {tensor2_1.device}") # int -> type casting

tensor2_2 = torch.from_numpy(numpy_data).float()
print('====================================')

print(tensor2_2)
print(f"tensor type: {type(tensor2_2)}, tensor shape: {tensor2_2.shape}")
print(f"tensor dtype: {tensor2_2.dtype}, tensor device: {tensor2_2.device}")

tensor([[10, 20],
        [30, 40]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.int64, tensor device: cpu
tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cpu


In [12]:
tensor3 = torch.rand(2,2)
print(tensor3)

tensor4 = torch.randn(2,2) # 정규분포 (0,1) 에서 랜덤 샘플링 -> 자주 쓰임
print(tensor4)
print('====================================')
tensor5 = torch.randn(2, 2)
print(tensor5)

numpy_from_tensor = tensor5.numpy()
print(numpy_from_tensor) # tensor에서 numpy 배열로 바꾸는 방법

tensor([[0.1914, 0.4198],
        [0.2155, 0.8914]])
tensor([[-1.0429,  0.0426],
        [ 0.3475,  0.5117]])
tensor([[-0.4611,  1.5066],
        [ 1.4222, -0.4671]])
[[-0.461085    1.5066316 ]
 [ 1.4221559  -0.46713454]]


### tensor 연산

In [13]:
tensor6 = torch.Tensor([[1,2,3], [4,5,6]])
tensor7 = torch.Tensor([[7,8,9], [10,11,12]])

print(tensor6[0])
print(tensor6[:, 1:])
print(tensor7[0:2, 0:-1])
print(tensor7[-1, -1])
print(tensor7[... , -2])

tensor([1., 2., 3.])
tensor([[2., 3.],
        [5., 6.]])
tensor([[ 7.,  8.],
        [10., 11.]])
tensor(12.)
tensor([ 8., 11.])


In [14]:
tensor8 = tensor6.mul(tensor7)

print(tensor8)

tensor([[ 7., 16., 27.],
        [40., 55., 72.]])


In [15]:
tensor9 = tensor6.matmul(tensor7) # tensor6 @ tensor 7 계산 불가 -> 배열 바꿔야

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [16]:
tensor7.view(3,2)

tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [17]:
tensor9 = tensor6.matmul(tensor7.view(3,2))
print(tensor9)

tensor([[ 58.,  64.],
        [139., 154.]])


### Tensor 합치기 (Concatenate)

In [19]:
tensor_cat = torch.cat([tensor6, tensor7])
print(tensor_cat)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [21]:
tensor_cat_dim0 = torch.cat([tensor6, tensor7], dim = 0)
print(tensor_cat_dim0)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [22]:
tensor_cat_dim1 = torch.cat([tensor6, tensor7], dim = 1)
print(tensor_cat_dim1)

tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])
