<a href="https://colab.research.google.com/github/ymk713/Pytorch_study/blob/main/0527)DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 데이터 정의

In [1]:
import torch

x_train = torch.Tensor([2, 4, 6, 8, 10,
                        12, 14, 16, 18, 20]).view(10,1)
y_train = torch.Tensor([0, 0, 0, 0, 0,
                        0, 1, 1, 1, 1]).view(10,1)

print(x_train.shape, y_train.shape)

torch.Size([10, 1]) torch.Size([10, 1])


## 신경망 모델 구축

In [2]:
from torch import nn

class MyDeepLearningModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.deeplearning_stack = nn.Sequential(
            nn.Linear(1, 8), # 은닉층
            nn.Linear(8,1),  # 출력층
            nn.Sigmoid()
        )
    def forward(self, data):
        prediction = self.deeplearning_stack(data)
        return prediction

In [3]:
deeplearning_model = MyDeepLearningModel() # 모델 인스턴스 생성

for name, child in deeplearning_model.named_children():
    for param in child.parameters():
        print(name, param)

deeplearning_stack Parameter containing:
tensor([[ 0.3297],
        [-0.5254],
        [-0.9999],
        [ 0.7523],
        [-0.2068],
        [ 0.1876],
        [ 0.5561],
        [-0.1928]], requires_grad=True)
deeplearning_stack Parameter containing:
tensor([-0.3528,  0.5525,  0.2207,  0.9438,  0.9379, -0.7569, -0.4682,  0.0495],
       requires_grad=True)
deeplearning_stack Parameter containing:
tensor([[ 0.2012, -0.0335,  0.3496,  0.3062,  0.3133, -0.1889,  0.2655, -0.2794]],
       requires_grad=True)
deeplearning_stack Parameter containing:
tensor([0.2607], requires_grad=True)


In [4]:
loss_function = nn.BCELoss()

optimizer = torch.optim.SGD(deeplearning_model.parameters(), lr = 1e-1)

In [5]:
nums_epoch = 5000
for epoch in range(nums_epoch+1):
    outputs = deeplearning_model(x_train)
    loss = loss_function(outputs, y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch%100 == 0:
        print('epoch = ', epoch, ' current loss = ', loss.item())

epoch =  0  current loss =  0.979475200176239
epoch =  100  current loss =  0.40507760643959045
epoch =  200  current loss =  0.32023540139198303
epoch =  300  current loss =  0.27123698592185974
epoch =  400  current loss =  0.2385093718767166
epoch =  500  current loss =  0.2147645503282547
epoch =  600  current loss =  0.19658029079437256
epoch =  700  current loss =  0.18211199343204498
epoch =  800  current loss =  0.1702658236026764
epoch =  900  current loss =  0.16034767031669617
epoch =  1000  current loss =  0.15189339220523834
epoch =  1100  current loss =  0.14458107948303223
epoch =  1200  current loss =  0.13817651569843292
epoch =  1300  current loss =  0.1325085461139679
epoch =  1400  current loss =  0.1274467259645462
epoch =  1500  current loss =  0.12289055436849594
epoch =  1600  current loss =  0.11876138299703598
epoch =  1700  current loss =  0.11499576270580292
epoch =  1800  current loss =  0.1115436777472496
epoch =  1900  current loss =  0.10836233198642731


In [6]:
for name, child in deeplearning_model.named_children():
    for param in child.parameters():
        print(name, param)

deeplearning_stack Parameter containing:
tensor([[ 0.2323],
        [-0.3131],
        [-0.0937],
        [-0.3968],
        [-0.4344],
        [ 0.3631],
        [ 0.3132],
        [-0.0846]], requires_grad=True)
deeplearning_stack Parameter containing:
tensor([-2.5194,  3.3952,  1.0160,  4.3035,  4.7113, -3.9376, -3.3963,  0.9169],
       requires_grad=True)
deeplearning_stack Parameter containing:
tensor([[ 0.8101, -1.0917, -0.3267, -1.3838, -1.5149,  1.2661,  1.0921, -0.2948]],
       requires_grad=True)
deeplearning_stack Parameter containing:
tensor([-5.5078], requires_grad=True)


## test data 이용한 예측

In [7]:
deeplearning_model.eval() # 신경망을 추론 모드로 변환
test_data = torch.Tensor([0.5, 3.0, 3.5, 11.0, 13.0, 31.0]).view(6,1)

pred = deeplearning_model(test_data) # 6개의 test_data 에 대해 예측 실행
logical_value = (pred > 0.5).float() # 예측값이 0.5 초과하면 True 값을 실수 1.0으로 type casting
                                     # 예측값이 0.5 이하이면 False 값을 실수 0.0으로 type casting

print(pred)
print(logical_value)

tensor([[8.9516e-15],
        [5.8726e-12],
        [2.1489e-11],
        [6.0309e-03],
        [5.2103e-01],
        [1.0000e+00]], grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.]])



**결과해석**

입력 데이터가 12 이하인 0.5, 3.0, 3.5, 11.0에 대해서는 0을 예측하고,
14 이상이면 1을 예측함.
13에 대해서는 약 52.1%확률로 1을 예측함

